#spring:
#  datasource:
#    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/quest_db}
#    username: ${DBMS_USERNAME:root}
#    password: ${DBMS_PASSWORD:root}
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://103.200.23.139:3306/phamphu2_bookara
    username: phamphu2_bookara
    password: 6OunUb}U?vqd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
api:
  comic:
    url: "https://otruyenapi.com/v1/api/"


jwt:
  signerKey: "lF1vRrEJQEFMGXokV+Tq4EKuQ1xSobIoxTwd7JtVCf39mdfYsLY4rgUZaXW+gUB9"
  valid-duration: 3000000 #in second
  refreshable-duration: 3000000 # in seconds

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1069415166491-6ocvvf6vtbmj3epfju5mlksp2maaonrl.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8080